export const BADGES = [
  {
    name: 'Попкорн',
    category: 'popcorn',
    checked: false
  },
  {
    name: 'Спортивный напиток',
    category: 'sport',
    checked: false

  },
  {
    name: 'Картонки',
    category: 'cartons',
    checked: false

  },
  {
    name: 'Кофе колдбрю',
    category: 'coffee',
    checked: false

  },
  {
    name: 'Сладкая вата',
    category: 'vata',
    checked: false

  },
  {
    name: 'Спреи',
    category: 'spay',
    checked: false

  },
  {
    name: 'Ароматизированные бочки',
    category: 'bochki',
    checked: false

  },
  {
    name: 'Ароматизированные мешки',
    category: 'meshki',
    checked: false
  },


]


export const PRODUCTS = [
  {
    id: 1,
    name: 'Попкорн "Карамель"',
    description: 'High-quality sound with noise cancellation',
    price: 129.99,
    count:"12шт",
    sku: 'SKU-WH-001',
    category: 'popcorn',
    image: '/popcorn/karamel.jpg',
  },
  {
    id: 11,
    name: 'Попкорн "Шоколадный"',
    description: 'High-quality sound with noise cancellation',
    price: 129.99,
    count: "12шт",
    sku: 'SKU-WH-001',
    category: 'popcorn',
    image: '/popcorn/shokolad.jpg',
  },
  {
    id: 111,
    name: 'Попкорн "Сладкий"',
    description: 'High-quality sound with noise cancellation',
    price: 129.99,
    count: "12шт",
    sku: 'SKU-WH-001',
    category: 'popcorn',
    image: '/popcorn/sladkiy.jpg',
  },
  {
    id: 1111,
    name: 'Попкорн в стакане "Шоколадный"',
    description: 'High-quality sound with noise cancellation',
    price: 129.99,
    count: "20шт",
    sku: 'SKU-WH-001',
    category: 'popcorn',
    image: '/popcorn/stakan.jpg',
  },
  {
    id: 2,
    name: 'Sportinia BCAA "Апельсин"',
    description: 'Quick charging technology, universal compatibility',
    price: 24.99,
    sku: 'SKU-CH-002',
    count: "12шт",
    category: 'sport',
    image: '/sportinia/bca-2.webp',
  },
  {
    id: 22,
    name: 'Sportinia BCAA "Маракуя"',
    description: 'Quick charging technology, universal compatibility',
    price: 24.99,
    sku: 'SKU-CH-002',
    count: "12шт",
    category: 'sport',
    image: '/sportinia/bca-1.webp',
  },
  {
    id: 223,
    name: 'Sportinia L-carnitine "Ананас"',
    description: 'Quick charging technology, universal compatibility',
    price: 24.99,
    sku: 'SKU-CH-002',
    count: "12шт",
    category: 'sport',
    image: '/sportinia/L-car-1.webp',
  },
  {
    id: 224,
    name: 'Sportinia L-carnitine "Малина"',
    description: 'Quick charging technology, universal compatibility',
    price: 24.99,
    sku: 'SKU-CH-002',
    count: "12шт",
    category: 'sport',
    image: '/sportinia/L-car-2.webp',
  },
  {
    id: 225,
    name: 'Sportinia L-carnitine "Апельсин"',
    description: 'Quick charging technology, universal compatibility',
    price: 24.99,
    sku: 'SKU-CH-002',
    count: "12шт",
    category: 'sport',
    image: '/sportinia/L-car-2.webp',
  },
  {
    id: 226,
    name: 'Sportinia Vitamine C "Апельсин/Яблоко/Груша"',
    description: 'Quick charging technology, universal compatibility',
    price: 24.99,
    sku: 'SKU-CH-002',
    count: "12шт",
    category: 'sport',
    image: '/sportinia/V-c-1.webp',
  },

  {
    id: 5,
    name: 'Сладкая вата',
    description: 'Tempered glass, easy installation',
    price: 9.99,
    count: "20шт",
    sku: 'SKU-SP-005',
    category: 'vata',
    image: '/popcorn/vata.jpg',
  },
  {
    id: 6,
    name: 'Картонка аромат "Imperatrice"',
    description: 'Ergonomic design, precision tracking',
    price: 120,
    count: "1шт",
    sku: 'SKU-MS-006',
    category: 'cartons',
    image: '/aroma/k-imperatrice.webp',
  },
  {
    id: 61,
    name: 'Картонка аромат "Invictus"',
    description: 'Ergonomic design, precision tracking',
    price: 120,
    count: "1шт",
    sku: 'SKU-MS-006',
    category: 'cartons',
    image: '/aroma/k-invictus.webp',
  },
  {
    id: 62,
    name: 'Картонка аромат "Invictus"',
    description: 'Ergonomic design, precision tracking',
    price: 250,
    count: "1шт",
    sku: 'SKU-MS-006',
    category: 'cartons',
    image: '/aroma/k-sauvage.webp',
  },
  {
    id: 7,
    name: 'Бочка аромат "Lacoste"',
    description: 'Ergonomic design, precision tracking',
    price: 240,
    count: "1шт",
    sku: 'SKU-MS-011',
    category: 'bochki',
    image: '/aroma/b-lacoste.webp',
  },
  {
    id: 72,
    name: 'Бочка аромат "Farenheit"',
    description: 'Ergonomic design, precision tracking',
    price: 240,
    count: "1шт",
    sku: 'SKU-MS-011',
    category: 'bochki',
    image: '/aroma/b-FARENHEIT.webp',
  },
  {
    id: 78,
    name: 'Мешок аромат "invictus"',
    description: 'Ergonomic design, precision tracking',
    price: 240,
    count: "1шт",
    sku: 'SKU-MS-012',
    category: 'meshki',
    image: '/aroma/m-invictus.webp',
  },
  {
    id: 79,
    name: 'Мешок аромат "Lacoste"',
    description: 'Ergonomic design, precision tracking',
    price: 240,
    count: "1шт",
    sku: 'SKU-MS-012',
    category: 'meshki',
    image: '/aroma/m-lacoste.webp',
  },
  {
    id: 8,
    name: 'Cold brew "Апельсин"',
    description: 'Ergonomic design, precision tracking',
    price: 1500,
    count: "10шт",
    sku: 'SKU-MS-007',
    category: 'coffee',
    image: '/coffee/c-apelsin.webp',
  },
  {
    id: 82,
    name: 'Cold brew "Малина"',
    description: 'Ergonomic design, precision tracking',
    price: 1500,
    count: "10шт",
    sku: 'SKU-MS-007',
    category: 'coffee',
    image: '/coffee/c-malina.webp',
  },
  {
    id: 84,
    name: 'Cold brew "Гранат"',
    description: 'Ergonomic design, precision tracking',
    price: 1500,
    count: "10шт",
    sku: 'SKU-MS-007',
    category: 'coffee',
    image: '/coffee/c-granat.webp',
  },
  {
    id: 85,
    name: 'Cold brew "Вишня"',
    description: 'Ergonomic design, precision tracking',
    price: 1500,
    count: "10шт",
    sku: 'SKU-MS-007',
    category: 'coffee',
    image: '/coffee/c-vishnya.webp',
  },
  {
    id: 86,
    name: 'Cold brew "Черника"',
    description: 'Ergonomic design, precision tracking',
    price: 1500,
    count: "10шт",
    sku: 'SKU-MS-007',
    category: 'coffee',
    image: '/coffee/c-chernika.webp',
  },

  // {
  //   id: 8,
  //   name: 'Ароматизированные мешки',
  //   description: '7-port expansion, high-speed data transfer',
  //   price: 49.99,
  //   sku: 'SKU-UH-008',
  //   category: 'meshki',
  //   image: '/usb-hub.png',
  // },
]